export const DELETE_ITEM = 'DELETE_ITEM'
export const DELETE_ALL_ITEMS = 'DELETE_ALL_ITEMS'
export const EDIT_ITEM = 'EDIT_ITEM'
export const EDITING_ITEM = 'EDITING_ITEM'
export const CHECK_ITEM = 'CHECK_ITEM'
export const ADD_ITEM = 'ADD_ITEM'